// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageClient } from "./MessageClient";
import type { TransferAction } from "./TransferAction";

export type Message = { "Lib": { action: TransferAction, } } | { "Client": MessageClient };
