// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferKind } from "./TransferKind";
import type { TransferMetadata } from "./TransferMetadata";
import type { TransferState } from "./TransferState";

export type MessageClient = { kind: TransferKind, state: TransferState | null, metadata: TransferMetadata | null, };
