// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransferPayload = { "Files": Array<string> } | { "Text": string } | { "Url": string } | { "Wifi": { ssid: string, password: string, security_type: number, } };
