// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteDeviceInfo } from "./RemoteDeviceInfo";
import type { TransferPayload } from "./TransferPayload";
import type { TransferPayloadKind } from "./TransferPayloadKind";

export type TransferMetadata = { id: string, source: RemoteDeviceInfo | null, pin_code: string | null, payload_kind: TransferPayloadKind, 
/**
 * Only exists for Text data
 */
payload_preview: string | null, payload: TransferPayload | null, total_bytes: bigint, ack_bytes: bigint, };
